# Copyright (C) 2025  BakersDozenBagels

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

[manifest]
version = "1.0.0"
priority = 999

# Adds colors
[[patches]]
[patches.pattern]
target = "globals.lua"
pattern = "RENTAL = HEX('b18f43'),"
position = "after"
match_indent = true
payload = '''
BIASEDBALANCE_TEAL = HEX('79bbc3'),
BIASEDBALANCE_TANGERINE= HEX('fd8d3c'),

'''

[[patches]]
[patches.pattern]
target = "functions/misc_functions.lua"
pattern = "G.ARGS.LOC_COLOURS = G.ARGS.LOC_COLOURS or {"
position = "after"
match_indent = true
payload = '''
  biasedbalance_teal = G.C.BIASEDBALANCE_TEAL,
  biasedbalance_tangerine = G.C.BIASEDBALANCE_TANGERINE,
  
'''

# Omen Globe tweak
[[patches]]
[patches.pattern]
target = '=[SMODS _ "src/game_object.lua"]'
pattern = '_card = {set = "Planet", area = G.pack_cards, skip_materialize = true, soulable = true, key_append = "pl1"}'
position = 'before'
match_indent = true
payload = '''
if G.GAME.used_vouchers.v_omen_globe and pseudorandom('omen_globe') > 0.75 then
    _card = {set = "Spectral", area = G.pack_cards, skip_materialize = true, soulable = true, key_append = "pl2"}
else
'''
times = 1

[[patches]]
[patches.pattern]
target = '=[SMODS _ "src/game_object.lua"]'
pattern = '_card = {set = "Planet", area = G.pack_cards, skip_materialize = true, soulable = true, key_append = "pl1"}'
position = 'after'
match_indent = true
payload = 'end'
times = 1

# Magic Trick tweak
[[patches]]
[patches.regex]
target = 'functions/UI_definitions.lua'
pattern = "\\(G\\.GAME\\.used_vouchers\\[\"v_illusion\"\\] and pseudorandom\\(pseudoseed\\('illusion'\\)\\) > 0\\.6\\) and 'Enhanced' or 'Base'"
position = 'at'
payload = 'BiasedBalance and BiasedBalance.magic_trick()'
times = 1

# Illusion tweak
[[patches]]
[patches.regex]
target = 'functions/UI_definitions.lua'
pattern = "\\(v\\.type == 'Base' or v\\.type == 'Enhanced'\\) and G\\.GAME\\.used_vouchers\\[\"v_illusion\"\\] and pseudorandom\\(pseudoseed\\('illusion'\\)\\) > 0\\.8"
position = 'at'
payload = 'BiasedBalance and BiasedBalance.illusion(card, v.type)'
times = 1

# Common/Rare Tag tweak
[[patches]]
[patches.pattern]
target = 'card.lua'
pattern = 'self.ability.perishable = true'
position = 'at'
match_indent = true
payload = 'self.ability.perishable = _perishable'
times = 1

# Boss Tag tweak
[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = "-- TARGET: setting_blind effects"
position = "after"
match_indent = true
times = 1
payload = "if BiasedBalance then BiasedBalance.on_set_blind(G.GAME.blind) end"

# Blunted Impact w/o Talisman
[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = "-- TARGET: effects after hand evaluation"
position = "after"
match_indent = true
times = 1
payload = "if not Talisman then G.GAME.biasedBalance_priorHand = text end"

# Blue Stake Tweak
[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = "G.GAME.current_round.reroll_cost = (G.GAME.round_resets.temp_reroll_cost or G.GAME.round_resets.reroll_cost) + G.GAME.current_round.reroll_cost_increase"
position = "after"
match_indent = true
times = 1
payload = "* (BiasedBalance and BiasedBalance.reroll_scale() or 1)"

# Jumbo
[[patches]]
[patches.regex]
target = "functions/button_callbacks.lua"
pattern = "card\\.edition and card\\.edition\\.card_limit or 0"
position = "at"
root_capture = "0"
times = 4
payload = "(card.edition and card.edition.card_limit or 0) + (card.config.center.key == 'j_biasedBalance_Jumbo' and -1 or 0)"

[[patches]]
[patches.regex]
target = '=[SMODS _ "src/utils.lua"]'
pattern = "card\\.edition and card\\.edition\\.card_limit or 0"
position = "at"
root_capture = "0"
times = 1
payload = "(card.edition and card.edition.card_limit or 0) + (card.config.center.key == 'j_biasedBalance_Jumbo' and -1 or 0)"

# Patch For Recipe and Trade Secret
[[patches]]
[patches.pattern]
target = "card.lua"
pattern = "G.GAME.pack_choices = self.ability.choose or self.config.center.config.choose or 1"
position = "after"
payload = '''
if G.GAME.v_biasedBalance_recipe or G.GAME.v_biasedBalance_trade_secret then
    self.ability.extra = self.ability.extra + (G.GAME.v_biasedBalance_recipe or G.GAME.v_biasedBalance_trade_secret)
    G.GAME.pack_choices = G.GAME.pack_choices + (G.GAME.v_biasedBalance_recipe or G.GAME.v_biasedBalance_trade_secret)
    G.GAME.v_biasedBalance_recipe = nil
    G.GAME.v_biasedBalance_trade_secret = nil
end
G.GAME.pack_size = self.ability.extra
'''
match_indent = true

# Patch for Red Card
[[patches]]
[patches.pattern]
target = "card.lua"
pattern = "if self.ability.name == 'Red Card' and not context.blueprint then"
position = "at"
payload = '''
if False then
'''
match_indent = true

# Patch for Hologram
[[patches]]
[patches.pattern]
target = "card.lua"
pattern = "if self.ability.name == 'Hologram' and (not context.blueprint)"
position = "at"
payload = '''
if False
'''
match_indent = true

# Patch for Square Joker
[[patches]]
[patches.pattern]
target = "card.lua"
pattern = "if self.ability.name == 'Square Joker' and #context.full_hand == 4 and not context.blueprint then"
position = "at"
payload = '''
if False then
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "card.lua"
pattern = "if self.ability.name == 'Square Joker' then"
position = "at"
payload = '''
if False then
'''
match_indent = true

# Patch for Dusk
[[patches]]
[patches.pattern]
target = "card.lua"
pattern = "elseif self.ability.name == 'Dusk' then loc_vars = {self.ability.extra+1}"
position = "at"
payload = '''
elseif self.ability.name == 'Dusk' then loc_vars = loc_vars
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "card.lua"
pattern = "if self.ability.name == 'Dusk' and G.GAME.current_round.hands_left == 0 then"
position = "at"
payload = '''
if False then
'''
match_indent = true

# Patch for Ankh
[[patches]]
[patches.pattern]
target = "card.lua"
pattern = '''if self.ability.name == 'Ankh' then 
        if #G.jokers.cards >= G.jokers.config.card_limit then  '''
position = "at"
payload = '''
if self.ability.name == 'Ankh' then 
    if #G.jokers.cards - 1 >= G.jokers.config.card_limit then 
'''
match_indent = true

# Patch for Smurf
[[patches]]
[patches.pattern]
target = '''=[SMODS _ "src/overrides.lua"]'''
pattern = '''
	local temp_in_pool = {}
    for k, v in ipairs(G.P_CENTER_POOLS['Booster']) do
'''
position = "at"
payload = '''
	local temp_in_pool = {}
	
	local booster_pool = {}
	if #SMODS.find_card('j_biasedBalance_Smurf') > 0 then
		for k, v in ipairs(G.P_CENTER_POOLS['Booster']) do
			if string.match(v.key, "mega") then
				booster_pool[#booster_pool + 1] = v
			end
		end
	else
		booster_pool = G.P_CENTER_POOLS['Booster']
	end
	
    for k, v in ipairs(booster_pool) do
'''
match_indent = true

# Patch for Planet Tycoon
[[patches]]
[patches.pattern]
target = "card.lua"
pattern = "if center_table.name == 'Planet Merchant' or center_table.name == 'Planet Tycoon' then"
position = "at"
payload = '''
if center_table.name == 'Planet Merchant' then
'''
match_indent = true

# Patch for Retcon
[[patches]]
[patches.pattern]
target = "functions/button_callbacks.lua"
pattern = "(G.GAME.used_vouchers[\"v_retcon\"] or"
position = "at"
payload = '''
(
'''
match_indent = true


# Patch for Shy Joker
[[patches]]
[patches.pattern]
target = 'blind.lua'
pattern = '''function Blind:press_play()'''
position = 'after'
match_indent = true
payload = '''
if G.jokers then
    for _, v in pairs(G.jokers.cards) do
        if v.ability.name == "j_biasedBalance_Shy_Joker" then
			SMODS.change_play_limit(500)
			SMODS.change_discard_limit(500)
            G.E_MANAGER:add_event(Event({
                func = function()
                    local any_selected = nil
                    for _, playing_card in ipairs(G.hand.cards) do
                        if playing_card:is_face() then
                            G.hand:add_to_highlighted(playing_card, true)
                            any_selected = true
                        end
                    end
                	delay(0.7)
                    if any_selected then 
						play_sound('card1', 1) 
						G.FUNCS.discard_cards_from_highlighted(nil, true)
					end
                if any_selected then
                    v:juice_up(0.8, 0.8)
                end
                delay(0.7)
            return true end }))
			SMODS.change_play_limit(-500)
			SMODS.change_discard_limit(-500)
        end
    end
end
'''